collacc:
  build: ./collacc/
  command: ""
  ports:
    - 8083:80
  links:
    - db:mysql
  
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: collacc
    MYSQL_DATABASE: collacc
    MYSQL_USER: collacc
    MYSQL_PASSWORD: collacc
  volumes_from:
    - datadb

datadb:
  image: debian:jessie
  volumes:
    - /var/lib/mysql
  command: "true"
